### PR TITLE
Overlay gravity only top if on input screen

### LINKED ISSUE #406: Wrong gravity for dialog
To reproduce:
1. press IV button
2. expand appraisal (this will move the floating input window upward)
3. press Check IV (the window will move back down)
4. press button to inspect combinations (window stays down)
5. press back, and *the window moves incorrectly up* instead of staying down.

This sounds like the kind of bug you prevent by just separating the windows.

### PR DESCRIPTION
**Pull request by nahojjjen**
This commit makes the moveOverlayUpOrDownToMatchAppraisalBox method
always move the overlay down if the user is not on the input screen, as
it's not possible to end up in a situation where the appraisal box is
both intended to be expanded and not exist.

Fixes #406

### CODE REVIEW

File: app/src/main/java/com/kamron/pogoiv/Pokefly.java [hunk 1]
```diff
@@ -842,7 +842,14 @@ private void moveOverlayUpOrDownToMatchAppraisalBox() {
...
 
-        moveOverlay(appraisalBox.getVisibility() == View.VISIBLE);
+        if (inputBox.getVisibility() == View.VISIBLE) {
+            boolean appraisalExpanded = appraisalBox.getVisibility() == View.VISIBLE;
+            moveOverlay(appraisalExpanded);
+        } else { //always move overlay down if not on input screen. Appraisal box cant be open if user is not in
+            // input screen
+            moveOverlay(false);
+        }
+
```
Comment (Blaisorblade) [inline app/src/main/java/com/kamron/pogoiv/Pokefly.java]: Should this be `moveOverlay(inputBox.getVisibility() == View.VISIBLE && appraisalBox.getVisibility() == View.VISIBLE);` (with the same comment)?

**Comment by Blaisorblade** [comment]
Thanks for taking a look!

File: app/src/main/java/com/kamron/pogoiv/Pokefly.java (hunk 1 above)
Comment (nahojjjen) [inline app/src/main/java/com/kamron/pogoiv/Pokefly.java]: > moveOverlay(inputBox.getVisibility() == View.VISIBLE && appraisalBox.getVisibility() == View.VISIBLE);

That would check two booleans:

1. the user is viewing the input box
2. the user has expanded the appraisal box.

Checking both of those is not necessary, as it's not possible for the user to be viewing the appraisal box if the input box is not visible. This is because the appraisal box is **within** the input box, so if the input box is invisible, the appraisal box is always invisible.

Comment (Blaisorblade) [inline app/src/main/java/com/kamron/pogoiv/Pokefly.java]: Nope, because `&&` is short-circuiting — the second would be tested only if the first is true. It's just more concise.

Comment (nahojjjen) [inline app/src/main/java/com/kamron/pogoiv/Pokefly.java]: I didn't mean how the program ran the check, I thought you meant that I should add moveOverlay(inputBox.getVisibility() == View.VISIBLE && appraisalBox.getVisibility() == View.VISIBLE); to replace line 850, which wouldn't help much, which I explained by referring to that the possibility would never be possible. 

Do you mean that the if-else block should be replaced by 
moveOverlay(inputBox.getVisibility() == View.VISIBLE && appraisalBox.getVisibility() == View.VISIBLE);?

In that case, the answer is yes, I think it could be.

Comment (Blaisorblade) [inline app/src/main/java/com/kamron/pogoiv/Pokefly.java]: Yep I talked about the whole if-else, sorry for the ambiguity.

**Comment by nahojjjen** [comment]
Amended commit to change to your suggestion.

File: app/src/main/java/com/kamron/pogoiv/Pokefly.java [hunk 2]
```diff
@@ -842,7 +842,8 @@ private void moveOverlayUpOrDownToMatchAppraisalBox() {
             return;
         }
 
-        moveOverlay(appraisalBox.getVisibility() == View.VISIBLE);
+        //move up if on input screen & appraisal box is open, else move down
+        moveOverlay(inputBox.getVisibility() == View.VISIBLE && appraisalBox.getVisibility() == View.VISIBLE);
```
Comment (Blaisorblade) [inline app/src/main/java/com/kamron/pogoiv/Pokefly.java]: LGTM.
